### ISSUE TITLE
White text on white background when in dark mode

### ISSUE THREAD

**Issue by AntonLydike** [A/obsidian-blog-theme#2]
Visiting the example page just shows white text on white background. This is only happening when the browser is in "dark mode".

I'm running Firefox 107.

![image](https://user-images.githubusercontent.com/14147713/207323052-29c5618a-7982-4c2c-9d66-b1c8d7e8ffc9.png)

**Comment by A** [comment]
Thanks much, missed this. Fixed now after almost 2 years :D
